"use client";
import { useEffect, useState } from 'react';
import type { ProjectDetailDTO } from '@/shared/types';
import { Tooltip } from '@/components/common/Tooltip';
import {
  Clock,
  Lightbulb,
  FileText,
  Music,
  Layers,
  FileCheck2,
  Mic,
  Smartphone,
  Globe,
  Sparkles,
  Slash,
  AudioLines,
  Droplet,
  Subtitles,
  LayoutTemplate,
  Megaphone,
} from 'lucide-react';
import { getLanguageFlag, getLanguageLabel, normalizeLanguageList, DEFAULT_LANGUAGE, type TargetLanguageCode } from '@/shared/constants/languages';
import { normalizeLanguageVoiceMap } from '@/shared/voices/language-voice-map';
import { useVoices } from '@/hooks/useVoices';
import { features } from '@/lib/feature-flags';
import { useAppLanguage } from '@/components/providers/AppLanguageProvider';
import type { AppLanguageCode } from '@/shared/constants/app-language';
import { localizeVoiceOption } from '@/components/main/voice-translations';

type Props = { creation: ProjectDetailDTO['creation']; template?: ProjectDetailDTO['template'] | null };

type SettingsBarCopy = {
  notAvailable: string;
  myCharacter: string;
  publicCharacter: string;
  autoCharacter: string;
  selectedCharacter: string;
  customVoice: string;
  autoVoice: string;
  templatePreviewSuffix: string;
  usingDefaultTemplate: string;
  templateDefault: string;
  verticalFormat: string;
  targetLanguage: string;
  multiLanguage: string;
  voiceSelection: string;
  voiceMix: string;
  autoCharacterTooltip: string;
  autoCharacterFallback: string;
  characterAutoSelected: string;
  characterFallback: string;
  characterDefault: string;
  scriptModeTooltip: string;
  ideaModeTooltip: string;
  scriptModeBadge: string;
  ideaModeBadge: string;
  timingFromScript: string;
  targetDuration: string;
  defaultMusicIncluded: string;
  noDefaultMusic: string;
  musicOn: string;
  musicOff: string;
  overlayOnTooltip: string;
  overlayOffTooltip: string;
  overlayOn: string;
  overlayOff: string;
  watermarkOnTooltip: string;
  watermarkOffTooltip: string;
  watermarkOn: string;
  watermarkOff: string;
  captionsOnTooltip: string;
  captionsOffTooltip: string;
  captionsOn: string;
  captionsOff: string;
  ctaOffTooltip: string;
  ctaOnTooltip: string;
  ctaOn: string;
  ctaOff: string;
  scriptAutoOnTooltip: string;
  scriptAutoOffTooltip: string;
  scriptAuto: string;
  scriptManual: string;
  voiceAutoOnTooltip: string;
  voiceAutoOffTooltip: string;
  voiceAuto: string;
  voiceManual: string;
  scriptCreationPrompt: string;
  scriptAvoidancePrompt: string;
  audioTonePrompt: string;
  autoGeneratedForProject: string;
  characterPreviewAlt: string;
};

const COPY: Record<AppLanguageCode, SettingsBarCopy> = {
  en: {
    notAvailable: 'N/A',
    myCharacter: 'My character',
    publicCharacter: 'Public character',
    autoCharacter: 'Auto character',
    selectedCharacter: 'Selected character',
    customVoice: 'Custom voice',
    autoVoice: 'Auto voice',
    templatePreviewSuffix: 'preview',
    usingDefaultTemplate: 'Using default template',
    templateDefault: 'Template: Default',
    verticalFormat: 'Vertical 9:16 format',
    targetLanguage: 'Target language',
    multiLanguage: 'Multi-language',
    voiceSelection: 'Voiceover voice selection',
    voiceMix: 'Voice mix',
    autoCharacterTooltip: 'Auto character (auto-generated from your story)',
    autoCharacterFallback: 'Auto character',
    characterAutoSelected: 'Character will be auto-selected',
    characterFallback: 'Character',
    characterDefault: 'Character: Default',
    scriptModeTooltip: 'Script mode: exact text used as-is',
    ideaModeTooltip: 'Idea mode: generated from your prompt',
    scriptModeBadge: 'Script',
    ideaModeBadge: 'Idea',
    timingFromScript: 'Timing comes from your script',
    targetDuration: 'Approximate target duration',
    defaultMusicIncluded: 'Default music included',
    noDefaultMusic: 'No default music',
    musicOn: 'Music: On',
    musicOff: 'Music: Off',
    overlayOnTooltip: 'Overlay will be added',
    overlayOffTooltip: 'No overlay',
    overlayOn: 'Overlay: On',
    overlayOff: 'Overlay: Off',
    watermarkOnTooltip: 'Watermark will be shown',
    watermarkOffTooltip: 'Watermark disabled',
    watermarkOn: 'Watermark: On',
    watermarkOff: 'Watermark: Off',
    captionsOnTooltip: 'Captions will be added',
    captionsOffTooltip: 'Captions disabled',
    captionsOn: 'Captions: On',
    captionsOff: 'Captions: Off',
    ctaOffTooltip: 'CTA disabled',
    ctaOnTooltip: 'CTA will be appended if available',
    ctaOn: 'CTA: On',
    ctaOff: 'CTA: Off',
    scriptAutoOnTooltip: 'Script auto-approval enabled',
    scriptAutoOffTooltip: 'Script requires approval',
    scriptAuto: 'Script: Auto',
    scriptManual: 'Script: Manual',
    voiceAutoOnTooltip: 'Voiceover auto-approval enabled',
    voiceAutoOffTooltip: 'Voiceover requires approval',
    voiceAuto: 'Voiceover: Auto',
    voiceManual: 'Voiceover: Manual',
    scriptCreationPrompt: 'Script creation prompt',
    scriptAvoidancePrompt: 'Script avoidance prompt',
    audioTonePrompt: 'Audio tone prompt',
    autoGeneratedForProject: 'Auto-generated for this project',
    characterPreviewAlt: 'Character preview',
  },
  ru: {
    notAvailable: 'Н/Д',
    myCharacter: 'Мой персонаж',
    publicCharacter: 'Публичный персонаж',
    autoCharacter: 'Автоперсонаж',
    selectedCharacter: 'Выбранный персонаж',
    customVoice: 'Свой голос',
    autoVoice: 'Автоголос',
    templatePreviewSuffix: 'превью',
    usingDefaultTemplate: 'Используется шаблон по умолчанию',
    templateDefault: 'Шаблон: по умолчанию',
    verticalFormat: 'Вертикальный формат 9:16',
    targetLanguage: 'Язык проекта',
    multiLanguage: 'Несколько языков',
    voiceSelection: 'Выбор голоса озвучки',
    voiceMix: 'Набор голосов',
    autoCharacterTooltip: 'Автоперсонаж (генерируется по вашему сюжету)',
    autoCharacterFallback: 'Автоперсонаж',
    characterAutoSelected: 'Персонаж будет выбран автоматически',
    characterFallback: 'Персонаж',
    characterDefault: 'Персонаж: по умолчанию',
    scriptModeTooltip: 'Режим сценария: текст используется без изменений',
    ideaModeTooltip: 'Режим идеи: сценарий генерируется по вашему запросу',
    scriptModeBadge: 'Сценарий',
    ideaModeBadge: 'Идея',
    timingFromScript: 'Тайминг берётся из вашего сценария',
    targetDuration: 'Примерная целевая длительность',
    defaultMusicIncluded: 'Музыка по умолчанию включена',
    noDefaultMusic: 'Музыка по умолчанию отключена',
    musicOn: 'Музыка: вкл',
    musicOff: 'Музыка: выкл',
    overlayOnTooltip: 'Оверлей будет добавлен',
    overlayOffTooltip: 'Без оверлея',
    overlayOn: 'Оверлей: вкл',
    overlayOff: 'Оверлей: выкл',
    watermarkOnTooltip: 'Водяной знак будет добавлен',
    watermarkOffTooltip: 'Водяной знак отключён',
    watermarkOn: 'Водяной знак: вкл',
    watermarkOff: 'Водяной знак: выкл',
    captionsOnTooltip: 'Субтитры будут добавлены',
    captionsOffTooltip: 'Субтитры отключены',
    captionsOn: 'Субтитры: вкл',
    captionsOff: 'Субтитры: выкл',
    ctaOffTooltip: 'Призыв к действию отключён',
    ctaOnTooltip: 'Призыв к действию будет добавлен при наличии',
    ctaOn: 'Призыв: вкл',
    ctaOff: 'Призыв: выкл',
    scriptAutoOnTooltip: 'Автоподтверждение сценария включено',
    scriptAutoOffTooltip: 'Сценарий требует подтверждения',
    scriptAuto: 'Сценарий: авто',
    scriptManual: 'Сценарий: вручную',
    voiceAutoOnTooltip: 'Автоподтверждение озвучки включено',
    voiceAutoOffTooltip: 'Озвучка требует подтверждения',
    voiceAuto: 'Озвучка: авто',
    voiceManual: 'Озвучка: вручную',
    scriptCreationPrompt: 'Подсказка для генерации сценария',
    scriptAvoidancePrompt: 'Ограничения для сценария',
    audioTonePrompt: 'Подсказка по тону озвучки',
    autoGeneratedForProject: 'Сгенерирован для этого проекта',
    characterPreviewAlt: 'Превью персонажа',
  },
};

const LANGUAGE_LABELS_BY_UI: Record<AppLanguageCode, Record<TargetLanguageCode, string>> = {
  en: {
    en: 'English',
    ru: 'Russian',
    es: 'Spanish',
    fr: 'French',
    de: 'German',
    pt: 'Portuguese',
    it: 'Italian',
  },
  ru: {
    en: 'Английский',
    ru: 'Русский',
    es: 'Испанский',
    fr: 'Французский',
    de: 'Немецкий',
    pt: 'Португальский',
    it: 'Итальянский',
  },
};

function getUiLanguageLabel(appLanguage: AppLanguageCode, code: string): string {
  const normalized = code.toLowerCase() as TargetLanguageCode;
  return LANGUAGE_LABELS_BY_UI[appLanguage][normalized] ?? getLanguageLabel(normalized);
}

const TEMPLATE_TITLE_TRANSLATIONS_RU: Record<string, string> = {
  'Basic Effects': 'Базовые эффекты',
};

function localizeTemplateTitle(title: string, appLanguage: AppLanguageCode): string {
  if (appLanguage !== 'ru') return title;
  return TEMPLATE_TITLE_TRANSLATIONS_RU[title] ?? title;
}

function localizeIncomingCharacterBadgeLabel(
  label: string | null | undefined,
  appLanguage: AppLanguageCode,
  t: SettingsBarCopy,
): string | null {
  const value = typeof label === 'string' ? label.trim() : '';
  if (!value) return null;
  if (appLanguage !== 'ru') return value;

  const normalized = value.toLowerCase();
  if (normalized === 'auto character') return t.autoCharacter;
  if (normalized === 'my character') return t.myCharacter;
  if (normalized === 'public character') return t.publicCharacter;
  if (normalized === 'selected character') return t.selectedCharacter;
  if (normalized === 'character: default') return t.characterDefault;

  return value;
}

function fmtDuration(sec: number | null | undefined, notAvailableLabel: string, appLanguage: AppLanguageCode) {
  if (!sec || sec <= 0) return notAvailableLabel;
  const m = Math.floor(sec / 60);
  const s = sec % 60;
  return m > 0 ? `${m}:${s.toString().padStart(2, '0')}` : `${s}${appLanguage === 'ru' ? 'с' : 's'}`;
}

export function ProjectSettingsBar({ creation, template }: Props) {
  const { language } = useAppLanguage();
  const t = COPY[language];
  const audioTonePromptEnabled = features.audioTonePromptEnabled;
  const d = creation || {};
  const { getByExternalId } = useVoices();
  const isScript = !!d.useExactTextAsScript;
  const [templatePreviewLoaded, setTemplatePreviewLoaded] = useState(false);
  useEffect(() => {
    setTemplatePreviewLoaded(false);
  }, [template?.previewImageUrl]);

  const char = d.characterSelection as any;
  const selectionSource = (char?.source ?? char?.type ?? null) as 'global' | 'user' | 'dynamic' | null;
  const hasAssignedCharacter = selectionSource === 'user' || selectionSource === 'global';
  const isAutoCharacter = selectionSource === 'dynamic';
  const incomingBadgeLabel = localizeIncomingCharacterBadgeLabel(char?.badgeLabel, language, t);
  const characterBadgeLabel =
    incomingBadgeLabel
    ?? (
      selectionSource === 'user'
        ? t.myCharacter
        : selectionSource === 'global'
          ? t.publicCharacter
          : isAutoCharacter
            ? t.autoCharacter
            : null
    );
  const rawDisplayLabel = typeof char?.displayLabel === 'string' ? char.displayLabel.trim() : null;
  const characterDisplayLabel = rawDisplayLabel && rawDisplayLabel.length > 0 ? rawDisplayLabel : null;
  const characterTooltipTitle = characterDisplayLabel ?? characterBadgeLabel ?? t.selectedCharacter;
  const characterTooltipSubtitle =
    characterDisplayLabel && characterBadgeLabel && characterDisplayLabel !== characterBadgeLabel ? characterBadgeLabel : null;
  const characterImageUrl = char?.imageUrl ?? null;

  const scriptCreationGuidance = d.scriptCreationGuidanceEnabled && d.scriptCreationGuidance?.trim()?.length
    ? d.scriptCreationGuidance.trim()
    : null;
  const scriptAvoidanceGuidance = d.scriptAvoidanceGuidanceEnabled && d.scriptAvoidanceGuidance?.trim()?.length
    ? d.scriptAvoidanceGuidance.trim()
    : null;
  const audioStyleGuidance = audioTonePromptEnabled && d.audioStyleGuidanceEnabled && d.audioStyleGuidance?.trim()?.length
    ? d.audioStyleGuidance.trim()
    : null;

  const languagesList = normalizeLanguageList((d as any).languages ?? (d as any).targetLanguage ?? DEFAULT_LANGUAGE, DEFAULT_LANGUAGE);
  const languageVoiceMap = normalizeLanguageVoiceMap((d as any)?.languageVoiceAssignments ?? null);
  const voiceRows = languagesList.map((code) => {
    const voiceId = languageVoiceMap[code as keyof typeof languageVoiceMap] ?? ((d as any)?.voiceId ?? null);
    const option = voiceId ? getByExternalId(voiceId) : null;
    const localizedVoice = option ? localizeVoiceOption(option, language) : null;
    return {
      code,
      label: getUiLanguageLabel(language, code),
      voiceLabel: localizedVoice?.title ?? (voiceId ? t.customVoice : t.autoVoice),
      isAuto: !voiceId,
    };
  });
  const templateTitle = template ? localizeTemplateTitle(template.title, language) : t.templateDefault;

  return (
    <div className="flex flex-col gap-3">
      <div className="flex flex-wrap items-center gap-2">
        <Tooltip
          content={template ? (
            <div className="w-[220px] space-y-2 text-white">
              <div className="text-sm font-medium leading-tight">{templateTitle}</div>
              <div className="overflow-hidden rounded-md border border-white/20 bg-white/5">
                <div className="relative aspect-[9/16] w-full">
                  {!templatePreviewLoaded ? (
                    <div className="absolute inset-0 skeleton" />
                  ) : null}
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={template.previewImageUrl}
                    alt={`${templateTitle} ${t.templatePreviewSuffix}`}
                    className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-200 ${templatePreviewLoaded ? 'opacity-100' : 'opacity-0'}`}
                    loading="lazy"
                    onLoad={() => setTemplatePreviewLoaded(true)}
                    onError={() => setTemplatePreviewLoaded(true)}
                  />
                </div>
              </div>
            </div>
          ) : t.usingDefaultTemplate}
          side="bottom"
          align="center"
        >
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <LayoutTemplate className="h-3.5 w-3.5" /> {templateTitle}
          </span>
        </Tooltip>

        <Tooltip content={t.verticalFormat}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Smartphone className="h-3.5 w-3.5" /> 9:16
          </span>
        </Tooltip>

        <Tooltip
          content={(() => {
            const codes = normalizeLanguageList((d as any).languages ?? (d as any).targetLanguage ?? DEFAULT_LANGUAGE, DEFAULT_LANGUAGE);
            if (codes.length > 1) {
              return (
                <div className="space-y-1">
                  {codes.map((code) => (
                    <div key={code} className="flex items-center gap-2">
                      <span>{getLanguageFlag(code)}</span>
                      <span>{getUiLanguageLabel(language, code)}</span>
                    </div>
                  ))}
                </div>
              );
            }
            const code = codes[0];
            return `${t.targetLanguage}: ${getLanguageFlag(code)} ${getUiLanguageLabel(language, code)}`;
          })()}
        >
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Globe className="h-3.5 w-3.5" />{' '}
            {(() => {
              const codes = normalizeLanguageList((d as any).languages ?? (d as any).targetLanguage ?? DEFAULT_LANGUAGE, DEFAULT_LANGUAGE);
              return codes.length > 1
                ? t.multiLanguage
                : getUiLanguageLabel(language, codes[0]);
            })()}
          </span>
        </Tooltip>

        <Tooltip content={voiceRows.length ? (
          <div className="space-y-1">
            {voiceRows.map((row) => (
              <div key={row.code} className="flex items-center gap-2">
                <span>{getLanguageFlag(row.code)}</span>
                <span>{row.voiceLabel}</span>
              </div>
            ))}
          </div>
        ) : t.voiceSelection}
        >
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Mic className="h-3.5 w-3.5" /> {voiceRows.length > 1 ? t.voiceMix : (voiceRows[0]?.voiceLabel ?? t.autoVoice)}
          </span>
        </Tooltip>

        <Tooltip
          content={hasAssignedCharacter ? (
            characterImageUrl ? (
              <div className="w-[220px] space-y-2 text-white">
                <div>
                  <div className="text-sm font-medium leading-tight">{characterTooltipTitle}</div>
                  {characterTooltipSubtitle ? (
                    <div className="text-xs text-white/80">{characterTooltipSubtitle}</div>
                  ) : null}
                </div>
                <div className="overflow-hidden rounded-md border border-white/20 bg-white/5">
                  <div className="relative aspect-[9/16] w-full">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={characterImageUrl}
                      alt={characterTooltipTitle || t.characterPreviewAlt}
                      className="absolute inset-0 h-full w-full object-cover"
                      loading="lazy"
                    />
                  </div>
                </div>
              </div>
            ) : (
              <div className="space-y-1 text-white">
                <div className="text-sm font-medium leading-tight">{characterTooltipTitle}</div>
                {characterTooltipSubtitle ? (
                  <div className="text-xs text-white/80">{characterTooltipSubtitle}</div>
                ) : null}
              </div>
            )
          ) : isAutoCharacter
            ? t.autoCharacterTooltip
            : (characterBadgeLabel || t.characterAutoSelected)}
        >
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            {isAutoCharacter ? (
              <>
                <Sparkles className="h-3.5 w-3.5" /> {characterBadgeLabel || t.autoCharacterFallback}
              </>
            ) : hasAssignedCharacter ? (
              <>
                <Megaphone className="h-3.5 w-3.5" /> {characterBadgeLabel || t.characterFallback}
              </>
            ) : (
              <>
                <Megaphone className="h-3.5 w-3.5" /> {t.characterDefault}
              </>
            )}
          </span>
        </Tooltip>

        <Tooltip content={isScript ? t.scriptModeTooltip : t.ideaModeTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            {isScript ? <FileText className="h-3.5 w-3.5" /> : <Lightbulb className="h-3.5 w-3.5" />}
            {isScript ? t.scriptModeBadge : t.ideaModeBadge}
          </span>
        </Tooltip>

        <Tooltip content={isScript ? t.timingFromScript : t.targetDuration}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Clock className="h-3.5 w-3.5" /> {fmtDuration(d.durationSeconds ?? null, t.notAvailable, language)}
          </span>
        </Tooltip>

        <Tooltip content={d.includeDefaultMusic ? t.defaultMusicIncluded : t.noDefaultMusic}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Music className="h-3.5 w-3.5" /> {d.includeDefaultMusic ? t.musicOn : t.musicOff}
          </span>
        </Tooltip>

        <Tooltip content={d.addOverlay ? t.overlayOnTooltip : t.overlayOffTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Layers className="h-3.5 w-3.5" /> {d.addOverlay ? t.overlayOn : t.overlayOff}
          </span>
        </Tooltip>
        <Tooltip content={d.watermarkEnabled ? t.watermarkOnTooltip : t.watermarkOffTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Droplet className="h-3.5 w-3.5" /> {d.watermarkEnabled === false ? t.watermarkOff : t.watermarkOn}
          </span>
        </Tooltip>
        <Tooltip content={d.captionsEnabled ? t.captionsOnTooltip : t.captionsOffTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Subtitles className="h-3.5 w-3.5" /> {d.captionsEnabled === false ? t.captionsOff : t.captionsOn}
          </span>
        </Tooltip>

        <Tooltip content={(d as any).includeCallToAction === false ? t.ctaOffTooltip : t.ctaOnTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Megaphone className="h-3.5 w-3.5" /> {(d as any).includeCallToAction === false ? t.ctaOff : t.ctaOn}
          </span>
        </Tooltip>

        <Tooltip content={d.autoApproveScript ? t.scriptAutoOnTooltip : t.scriptAutoOffTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <FileCheck2 className="h-3.5 w-3.5" /> {d.autoApproveScript ? t.scriptAuto : t.scriptManual}
          </span>
        </Tooltip>

        <Tooltip content={d.autoApproveAudio ? t.voiceAutoOnTooltip : t.voiceAutoOffTooltip}>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-gray-200 px-2 py-0.5 text-xs text-gray-700 dark:border-gray-800 dark:text-gray-200">
            <Mic className="h-3.5 w-3.5" /> {d.autoApproveAudio ? t.voiceAuto : t.voiceManual}
          </span>
        </Tooltip>
      </div>

      {(scriptCreationGuidance || scriptAvoidanceGuidance || audioStyleGuidance) ? (
        <div className="space-y-3 text-sm leading-6 text-gray-700 dark:text-gray-200">
          {scriptCreationGuidance ? (
            <div>
              <div className="mb-1 inline-flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">
                <Sparkles className="h-3.5 w-3.5" /> {t.scriptCreationPrompt}
              </div>
              <p className="whitespace-pre-wrap text-sm">{scriptCreationGuidance}</p>
            </div>
          ) : null}
          {scriptAvoidanceGuidance ? (
            <div>
              <div className="mb-1 inline-flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">
                <Slash className="h-3.5 w-3.5" /> {t.scriptAvoidancePrompt}
              </div>
              <p className="whitespace-pre-wrap text-sm">{scriptAvoidanceGuidance}</p>
            </div>
          ) : null}
          {audioStyleGuidance ? (
            <div>
              <div className="mb-1 inline-flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-gray-500 dark:text-gray-400">
                <AudioLines className="h-3.5 w-3.5" /> {t.audioTonePrompt}
              </div>
              <p className="whitespace-pre-wrap text-sm">{audioStyleGuidance}</p>
            </div>
          ) : null}
        </div>
      ) : null}

      {hasAssignedCharacter && characterImageUrl ? (
        <div className="mt-3">
          <Tooltip
            content={(
              <div className="max-w-[220px] text-xs leading-5 text-white">
                <div className="font-medium text-white/90">{characterTooltipTitle}</div>
                {characterTooltipSubtitle ? (
                  <div className="text-white/70">{characterTooltipSubtitle}</div>
                ) : null}
                {char?.generated ? (
                  <div className="mt-1 inline-flex items-center gap-1 rounded bg-white/15 px-1.5 py-0.5 text-[10px] font-medium text-white">
                    <Sparkles className="h-3 w-3" /> {t.autoGeneratedForProject}
                  </div>
                ) : null}
              </div>
            )}
          >
            <div className="inline-flex rounded-lg border border-gray-200 bg-gray-50 p-2 dark:border-gray-800 dark:bg-gray-900">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={characterImageUrl}
                alt={characterTooltipTitle || t.characterPreviewAlt}
                className="max-h-[300px] max-w-[300px] h-auto w-auto object-contain rounded"
                loading="lazy"
              />
            </div>
          </Tooltip>
        </div>
      ) : null}
    </div>
  );
}
